config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :ratings, only: [:show]
  end
  resources :progressions, only: [:index, :show] do
    post 'status' => 'progressions#status_update', as: :status_update
  end

  resources :payments, only: [:create, :show]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :course

  has_many :answers, dependent: :destroy
  validates :message, presence: { not_blank: 'ne doit pas être vide' }
  validates :message, length: { minimum: 10, too_short: "Votre message doit faire au minimum 10 charactères" }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :progressions, dependent: :destroy
  has_many :answers, through: :comments, dependent: :destroy
  has_many :users, through: :progression

  validates :title, presence: { not_blank: 'Humm... \'\' n\'est pas un bon titre ....' }
  validates :title, uniqueness: { not_uniq: 'Ce titre est déjà utilisé. Change !!!!'}
  validates :slug, uniqueness: { not_uniq: 'Ce slug est déjà utilisé. Fait gaff'}

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/progression.rb
class Progression < ApplicationRecord
  belongs_to :user
  belongs_to :course

  def status_visited_card
    return 'not-visited' if self.visited == false
  end

  def update_visite_status
    unless self.visited == true
      self.update!(visited: true)
    end
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user

  validates :rate, presence: { not_blank: 'Si tu sais pas quoi mettre, lache-toi avec un 5 étoiles ...' }
  validates :rate, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :progressions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :rating, dependent: :destroy
  has_one :payment, dependent: :destroy
  has_many :courses

  validates :first_name, :email, presence: { not_blank: 'Les champs sont vides... Applique toi !' }
  validates :email, :slug, uniqueness: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  after_action :redirect_course, only: [:create, :update, :destroy]
  before_action :
  def create
    @answer = authorize Answer.new(answer_params)
    @answer.user = current_user
    if @answer.save?
      redirect_to course_path(@answer.comment.course)
    else
      render :new
    end
  end

  def update
    @answer.update(answer_params)
    redirect_to course_path(@answer.comment.course)
  end

  def destroy
    @answer.destroy
    redirect_to course_path(@answer.comment.course)
  end

  private

  def find_answer
    @answer = authorize Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:message)
  end

  def redirect_course

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
  protect_from_forgery with: :exception

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?, :raise => false

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  def after_sign_in_path_for(resource)
    progressions_path
  end

  def after_sign_up_path_for(resource)
    progressions_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
end

app/controllers/progressions_controller.rb
class ProgressionsController < ApplicationController
  before_action :progressions_user, only: [:index, :show]
  before_action :progression_user, only: [:show, :update]

  def index
    # @progressions = policy_scope(Progression)
    @first_progression = @progressions.first
    @text_progressions = @progressions.offset(1).first(7)
    @business_progressions = @progressions.offset(8).first(10)
    @imbrication_progressions = @progressions.last(7)
    # raise
  end

  def show
    @progression.update_visite_status
  end

  def status_update
    progression = Progression.find(params[:progression_id])
    authorize progression
    progression.update!(status: true)
    redirect_to progression_path(progression.id.to_i + 1)
  end

  private


  def params_progression
    params.require(:progression).permit(:status)
  end

  def progressions_user
    @progressions = policy_scope(Progression)
  end

  def progression_user
    @progression =  Progression.find(params[:id])
    authorize @progression
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def youtube_video(progression)
    render :partial => 'shared/video', :locals => { progression: progression}
  end
end

app/helpers/progression_helper.rb
module ProgressionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exceltips</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to 'Se connecter', new_user_session_path %>
<%= link_to 'Créer un compte', new_user_registration_path %>
<%= link_to 'Cours', progressions_path %>

app/views/progressions/index.html.erb
<div class="wrapper-global">
  <%= render partial: 'shared/dashboard_one' %>
  <div class="container-courses">
    <div class="section-courses">
      <h3>Introduction</h3>
      <%= link_to progression_path(@first_progression) do %>
        <%= render partial: 'shared/card_large', locals: { progression: @first_progression } %>
      <% end %>
    </div>
    <div class="section-courses">
      <h3>Texte - Les indispensables</h3>
      <% @text_progressions.each do |progression| %>
        <%= link_to progression_path(progression) do %>
          <%= render partial: 'shared/card_large', locals: { progression: progression } %>
        <% end %>
      <% end %>
    </div>
    <div class="section-courses">
      <h3>Business - Les indispensables</h3>
      <% @business_progressions.each do |progression| %>
        <%= link_to progression_path(progression) do %>
          <%= render partial: 'shared/card_large', locals: { progression: progression } %>
        <% end %>
      <% end %>
    </div>
    <div class="section-courses">
      <h3>Imbrications - Les indispensables</h3>
      <% @imbrication_progressions.each do |progression| %>
        <%= link_to progression_path(progression) do %>
          <%= render partial: 'shared/card_large', locals: { progression: progression } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/progressions/show.html.erb
<%= render partial: 'shared/navbar_dashboard', locals: { progression: @progression }  %>
<div class="wrapper-global">
  <%= render partial: 'shared/dashboard_two', locals: { progression: @progression, progressions: @progressions }  %>
  <div id="display-progression">
    <div id="progression-header">
      <h5 id="title-progression"><%= @progression.course.title %></h5>
      <div class="progression-doc">
        <%= render partial: 'shared/file_course', locals: { progression: @progression } %>
        <%= render partial: 'shared/file_slip', locals: { progression: @progression } %>
        <%= render partial: 'shared/file_exercice', locals: { progression: @progression } %>
      </div>
    </div>
    <div id="progression-body">
      <%= youtube_video(@progression) %>
    </div>
    <div class="progression-footer">
    </div>
  </div>
</div>

app/views/shared/_card_large.html.erb
<div class="card-large <%= progression.status_visited_card %>">
  <img src="https://picsum.photos/seed/picsum/180/120" alt="">
  <div class="inside-card-large">
    <h6><%= progression.course.title %></h6>
    <p><%= progression.course.description %></p>
  </div>
  <div class="status-card">
    <% if progression.visited == false %>
      <i class="far fa-circle"></i>
    <% elsif progression.status == false %>
      <%= image_tag 'notdown'%>
    <% else %>
      <i class="fas fa-check-circle"></i>
    <% end %>
  </div>
</div>

app/views/shared/_card_small.html.erb
<div class="card-small <%= progression.status_visited_card %>">
  <div class="status-card">
    <% if progression.visited == false %>
      <i class="far fa-circle"></i>
    <% elsif progression.status == false %>
      <%= image_tag 'notdown'%>
    <% else %>
      <i class="fas fa-check-circle"></i>
    <% end %>
  </div>
  <div class="inside-card-small">
    <h6><%= progression.course.title %></h6>
  </div>
</div>

app/views/shared/_dashboard_one.html.erb
<div class="dashboard-one">
  <div class="progression-circle">
    <%= image_tag "logo_exceltips", class: 'logo-avatar' %>
    <%= render partial: 'shared/progression' %>
  </div>
  <div class="navigation-box">
    <div class="box active-dashboard">
      <!-- ADD LINK TO  -->
      <%#= link_to ....,  %>
      <i class="fas fa-book-open"></i>
      <p>Exceltips - Formation</p>
      <%# end %>
    </div>
    <div class="box">
      <!-- ADD LINK TO  -->
      <%#= link_to ....,  %>
      <i class="fas fa-user-graduate"></i>
      <p>Thomas - Professeur</p>
      <%# end %>
    </div>
  </div>
</div>

app/views/shared/_dashboard_two.html.erb
<div class="dashboard-two">
  <div class="progression-circle">
    <%= image_tag "logo_exceltips", class: 'logo-avatar' %>
    <%= render partial: 'shared/progression' %>
  </div>
  <div class="navigation-box">
    <% progressions.each do |progression| %>
      <%= link_to progression_path(progression) do %>
        <%= render partial: 'shared/card_small', locals: { progression: progression} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_file_course.html.erb
  <% unless progression.course.pdf_course.first == "" %>
  <% progression.course.pdf_course.each do |pdf| %>
    <%= link_to "#{pdf}", target: '_blank', class: "course-download" do %>
      <div class="doc-course">
        <i class="fas fa-book icon"></i>
        <p>Cours</p>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_file_exercice.html.erb
  <% unless progression.course.excel_course.first == "" %>
  <% progression.course.excel_course.each do |excel| %>
    <%= link_to "#{excel}", target: '_blank', class: "course-download" do %>
      <div class="doc-course">
        <i class="fas fa-book icon"></i>
        <p>Exercice</p>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_file_slip.html.erb
<% unless progression.course.pdf_slip.first == "" %>
  <% progression.course.pdf_slip.each do |slip| %>
    <%= link_to "#{slip}", target: '_blank', class: "course-download" do %>
      <div class="doc-course">
        <i class="fas fa-clipboard icon"></i>
        <p>Fiche</p>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_dashboard.html.erb
<div class="navbar-container">
  <% if progression.course.id == 1 %>
    <div class="grid-navbar-two">
      <div class="navbar-colorize">
        <%= link_to progressions_path, class: 'grid-inside', id: "first-column" do %>
          <i class="fas fa-chevron-circle-left"></i>
        <% end %>
      </div>
      <div class="navbar-colorize">
        <%= button_to progression_status_update_path(progression.id), class: 'grid-inside', id: 'complete-progression' do %>
          <div class="grid-transform" id="third-column-two">
            <p>Compléter et passer au cours suivant</p>
            <i class="fas fa-chevron-circle-right"></i>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="grid-navbar-three">
      <div class="navbar-colorize">
        <%= link_to progressions_path, class: "grid-inside", id:"first-column" do %>
          <i class="fas fa-chevron-circle-left"></i>
        <% end %>
      </div>
      <div class="navbar-colorize">
        <%= link_to progression_path(progression.id - 1), class: 'grid-inside' do %>
          <div class="grid-transform" id="second-column">
            <i class="fas fa-chevron-circle-left"></i>
            <p>Revenir au cours précédent</p>
          </div>
        <% end %>
      </div>
      <div class="navbar-colorize">
        <!-- schedule_visit_path(schedule, visit, visit: { status: "accepted"}), method: :patch, remote: :true -->
        <%= button_to progression_status_update_path(progression.id), class: 'grid-inside', id: 'complete-progression' do %>
          <div class="grid-transform" id="third-column">
            <p>Compléter et passer au cours suivant</p>
            <i class="fas fa-chevron-circle-right"></i>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_progression.html.erb
<div class="content">
  <div class="group">
    <div class="circular-progress100"></div>
  </div>
</div>

app/views/shared/_video.html.erb
<iframe width="490" height="275" src="<%= progression.course.video_url.first %>" frameborder="0" allowfullscreen></iframe>